data:
  batch_size: 30
  end_idx: 30
  info_dir: /projects/perception/datasets/animal_videos/version9/
  mesh_dir: /home/yuefanw/yuefanw/CASA_code/simplified_meshes/
  embedding_dir: ./dataset/embeddings
  input_dir: ./dataset
  out_dir: /home/yuefanw/scratch/test_optim_ske-camready_test
  retrieval_animal: giant_otter_female
  start_idx: 0
  test_animal: grey_seal_male
model:
  w_flow: 1000000
  w_mask: 10000
  w_smooth: 1000000
  w_symm: 10000
seed: 2000
type: real
