data:
  batch_size: 30
  embedding_dir: ./dataset/embeddings # path to stored embedding
  end_idx: 30
  info_dir: /projects/perception/datasets/animal_videos/version9/  # path to Planetzoo dataset
  mesh_dir: ./dataset/simplified_meshes/  # path to simplified meshes
  out_dir: /home/yuefanw/scratch/test_optim_ske-camready_test
  start_idx: 0
  test_animal: grey_seal_male
model:
  w_flow: 1000000
  w_mask: 10000
  w_smooth: 1000000
  w_symm: 10000
seed: 2000
type: synthetic
